expose_php = Off
memory_limit = 256M
upload_max_filesize = 16M
post_max_size = 64M
max_execution_time = 60
date.timezone = Asia/Jakarta

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 192
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.jit = tracing
opcache.jit_buffer_size = 64M

session.cookie_httponly = 1
session.use_strict_mode = 1
